# Generated by Django 3.0 on 2021-02-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210218_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='post.Tag'),
        ),
    ]
